### ISSUE TITLE
Regarding Class-wise forgetting

### ISSUE THREAD

**Issue by smallwangzi** [OPTML-Group/Unlearn-Sparse#10] opened 2024-10-12 08:20 UTC
Hello, I would like to ask a question regarding Class-wise forgetting. There is a significant difference between the results I obtained and those described in the paper. Can you help me out and tell me what the problem is?

`python -u main_forget.py --seed=1 --gpu 0 --data ./datasets/cifar10 --dataset cifar10 --save_dir './_results/cifat10' --mask ./omp/cifar10/1model_SA_best.pth.tar --print_freq=10 --unlearn FT --class_to_replace 0 --unlearn_epochs 10 --unlearn_lr 0.01`
<img width="777" alt="FT" src="https://github.com/user-attachments/assets/db428962-66fe-4500-a1bb-af366cd1c1f9">

<img width="675" alt="FF" src="https://github.com/user-attachments/assets/897c5b49-09b8-4f4a-ab9a-a169e91319ab">

**Comment by jinghanjia** [comment] 2024-11-16 16:11
I have replied this issue via email as follows. 

"Thank you for your interest in our paper. Based on the information provided, it’s difficult for me to determine the issue and help debug what’s happening.

There is, however, an existing issue where the results shown in https://github.com/OPTML-Group/Unlearn-Sparse/issues/4 have been successfully reproduced those results. You might want to check that for reference.

Could you please provide more details about the specific commands you ran? Since there is a large variance in class forgetting, it’s important to try running the process multiple times. Also, could you clarify how you obtained the sparse model?"

Since there hasn’t been a follow-up response via email, I’ll go ahead and close this issue for now. If you have further questions, feel free to reopen it or create a new one.

**Closed as completed by jinghanjia** 2024-11-16 16:11 UTC
